### ISSUE TITLE
Intermittent issues with real time adherence data/stack

### ISSUE THREAD

**Issue by djecht** [aws-quickstart/connect-integration-aspect-wfm#12]
The Lambda function created by the 'Real Time Adherence' Stack seems to intermittently error out when attempting to write agent states into DynamoDB. Once the error occurs, the Lambda function is unable to update DynamoDB.  The Lambda function is then continuously called by the Kinesis Data Stream with the same payload that produces the error. This stops within about 2 days, after which the Lambda function resumes working as normal.

I do not have a precise method to reproduce the error but I have not been able to conduct testing sessions (where I'm moving an agent within Amazon Connect through various states) for more than about 20 minutes before it occurs.

In a nutshell, if you:
- deploy a working (agent able to log in and change states) instance of Amazon Connect
- deploy this quickstart selecting the option to 'Deploy for real-time adherence' OR 'Deploy for both options'
- monitor either the Lambda function or DynamoDB objects created by the quickstart
- login to Amazon Connect as your agent and continue to change states

This error (message from Lambda > Cloudwatch logs below) should rear its head at some point.

---------
One or more errors occurred. (Unable to convert hash key value for property AgentARN): AggregateException
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Amazon.DynamoDBv2.DataModel.DynamoDBContext.MakeKey(Object hashKey, Object rangeKey, ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig)
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelperAsync[T](Object hashKey, Object rangeKey, DynamoDBOperationConfig operationConfig, CancellationToken cancellationToken)
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadAsync[T](Object hashKey, CancellationToken cancellationToken)
at AspectKinesisLamda.ProcessKinesisEvents.ProcessEventToTable(ConnectKinesisEventRecord streamRecord)
at AspectKinesisLamda.ProcessKinesisEvents.ProcessEventRecord(KinesisEventRecord record, Boolean writeEventsToQueue)
at AspectKinesisLamda.ProcessKinesisEvents.AspectKinesisHandler(KinesisEvent kinesisEvent, ILambdaContext context)
-------------

**Comment by DBurkhead** [comment]
@djecht The default read/write capacity for the DynamoDB table deployed by the RTA CloudFormation template is pretty small. I've seen cases where the capacity needed to be increased, depending on the volume of state changes. The default capacity is intended to limit charges in the case of a small, test system. You may need to adjust the capacity of your DynamoDB table. Check the Read Capacity and Write Capacity metrics on the Metrics tab of the DynamoDB table. You can adjust the capacity on the Capacity tab. You can either explicitly increase the provisioned capacity, enable auto scaling, or switch to on-demand mode and let AWS handle the provisioning.
I can't tell from the error whether this issue is related to exceeding the capacity of the DynamoDB table, but it's worth a shot.

**Comment by ashwanijha04** [comment]
Hi @DBurkhead 

Replication Steps: [https://aws.amazon.com/quickstart/connect/aspect-wfm/]


- Create an Amazon Connect Instance 
- From the above doc, Deploy for both options. [New Kinesis Stream]
- After the stack is created, look at the RTA Stack. [Step 4 asks us to enable Kinesis Data Stream]
- 'LambdaFunctionCloudTest' expects a Kinesis Stream type of data and raises an 'Object not found' exception when the request payload is wrong.
- Now, login to your connect instance(Create user is required). On clicking the small call button on the top right, a new window will be open.
- Changing the status to Available/Offline triggers the lambda function(by RTA).
- The function needs to write this data to DynamoDb but it throws an exception when it is not able to find the Records['Kinesis']['data'] object. Kinesis Stream type of data has this object but the RecordData does not have this and this is raising an exception.

**Comment by ashwanijha04** [comment]
Hi @DBurkhead

I have provided steps to re-create the error. Would you please help with this?

**Comment by DBurkhead** [comment]
@ashwanijha04 
The error you describe sounds like a configuration issue. How did you configure the Data streaming settings of your Amazon Connect? The Kinesis stream created by the RTA stack should be selected under Agent Events. It should not be selected for Contact Trace Records.

**Comment by ashwanijha04** [comment]
Thank you @DBurkhead. Your help is really appreciated. Could you please tell me what to do if I want to use both Contact Trace Records and Agent Events? Should I create a different kinesis stream for CTR? And if so, which lambda function should this kinesis stream trigger?

**Comment by DBurkhead** [comment]
@ashwanijha04 
Yes, I'd recommend that you create a different kinesis stream for Contact Trace Records (or kinesis firehose stream, depending on what you want to do with Contact Trace Records). The Lambda created by the RTA stack, LambdaFunctionCloudTest, should be associated with the Agent Events kinesis stream. Both of the deployment options associated with the Aspect Workforce Management AWS QuickStart depend on the Agent Events kinesis stream. The QuickStart does not create any Lambdas intended to consume the Contact Trace Records kinesis stream. If you want to do something in response to Contact Trace Records, you would need to create that Lambda (or hire someone to create that Lambda). A Lambda can be triggered by multiple kinesis streams, so you could configure this new Lambda to fire based on new Agent Events and new Contact Trace Records, if needed.

**Comment by ashwanijha04** [comment]
Thank you so much @DBurkhead 👍

**Comment by DBurkhead** [comment]
@djecht I was trying to reproduce the second scenario added to this issue, configuring both Contact Trace Records and Agent Events to feed the Kinesis stream associated with the RTA integration, and I got the error you listed above. If the Lambda created by the RTA integration gets a Contact Trace Record, it will attempt to parse it as an Agent Event record, get a null AgentARN, and then tries to add a row to the DynamoDB table for the null AgentARN, which results in the error listed above. A Contact Trace Record includes the agent ARN, but it's not in a top-level field called AgentARN; it's in the Agent/ARN field in the CTR JSON format.
If you have configured both Contact Trace Records and Agent Events to use the Kinesis stream associated with your RTA stack, I recommend that you disable the feed of Contact Trace Records. The Lambda created by the RTA stack expects all of the records it reads to match the Agent Event JSON format.

**Comment by djecht** [comment]
@DBurkhead Thanks so much for that, and apologies for the lack of update!
Turns out that i did have both Contact Trace Records and Agent Events being fed to the one Kinesis stream. I only had the one Kinesis stream created when I was enabling Data Streaming for Amazon Connect and I think GUI forces you to populate the CTR and Agent Event fields.

I haven't encountered the issue since separating the two!
