### ISSUE TITLE
Invalid CloudFormation template link on AWS QuickStart page

### ISSUE THREAD

**Issue by DBurkhead** [aws-quickstart/connect-integration-aspect-wfm#15]
The CloudFormation template filenames for this QuickStart were renamed recently. The template extensions were changed from .template to .template.yaml. Most of the links on the AWS QuickStart page were updated, but one was missed. It looks like the link under the left column (For a new Kinesis data stream) for Deploy real-time adherence is missing the .yaml.

**Comment by andrew-glenn** [comment]
No longer an issue. closing.
