### ISSUE TITLE
Requesting an update of the AWS QuickStart page for this repo

### ISSUE THREAD

**Issue by DBurkhead** [aws-quickstart/connect-integration-aspect-wfm#17]
@andrew-glenn can you merge the changes from the develop branch back to the master branch for this repo and push those changes out to the aws-quickstart S3 bucket(s)? One of Aspect's customers is about to deploy this integration, so we'd like to take advantage of these enhancements.

**Comment by DBurkhead** [comment]
@andrew-glenn following up in this issue. Can someone on the AWS QuickStart team merge my changes back to the master branch and publish the changes to the aws-quickstart S3 bucket(s)?

Let me know if I'm supposed to contact someone else.

**Comment by DBurkhead** [comment]
@sshvans @lucius-aws-quickstart 
The develop branch of this repository has some enhancements I checked in (and @andrew-glenn merged). Could one of you merge those changes to the master branch and then publish the changes to the aws-quickstart S3 bucket(s)?
These changes are intended to improve the performance of the interface between Connect and the Aspect Real-Time Adherence product. Some Aspect/Connect customers need these changes.

**Comment by vsnyc** [comment]
@DBurkhead - Done. Just for reference, we now use the main branch as opposed to master branch as the source for publishing.

**Comment by DBurkhead** [comment]
@vsnyc I just checked the AWS QuickStart page for this integration. It looks like everything is in place in the aws-quickstart S3 bucket. Thanks for the help.
