### ISSUE TITLE
Deployment fails after lambda-copyzips submodule changes

### ISSUE THREAD

**Issue by DBurkhead** [aws-quickstart/connect-integration-aspect-wfm#21]
I get the following error in CloudFormation if I try to create a stack using any of the CloudFormation templates of this integration.

<span><span>
2021-06-18 11:36:02 UTC-0500 | CopyZipsTemplate | &nbsp;
-- | -- | --

</span></span><span><span>
CREATE_FAILED | Value of property Parameters must be an object with String (or simple type) properties
-- | --

</span></span>

I assume that this error is a result of the latest commit:
https://github.com/aws-quickstart/connect-integration-aspect-wfm/commit/8f599b2a688425775decf32e4a7b3747cbda45e2

Which switched to running the copyzips Lambda from a submodule. Any ideas?

I also noticed that these copyzips changes are in main but they are not in develop. Would you merge the changes down to develop once the fix is in place?

Thanks.

**Comment by andrew-glenn** [comment]
Fixed via https://github.com/aws-quickstart/connect-integration-aspect-wfm/commit/d40732edacafad0f4d096f53d609f16a5c03e87c
